# Generated by Django 4.2.27 on 2026-03-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
