# Generated by Django 4.2.27 on 2026-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
    ]
