# Generated by Django 4.2.27 on 2026-03-03 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("event_reminders", models.BooleanField(default=True)),
                ("forum_digest", models.BooleanField(default=False)),
                ("direct_messages", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Member settings",
            },
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("home_style", models.CharField(blank=True, max_length=100)),
                ("home_year", models.PositiveIntegerField(blank=True, null=True)),
                ("home_name", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.URLField(blank=True, max_length=500)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("member_since", models.CharField(blank=True, max_length=10)),
                ("registry", models.CharField(blank=True, max_length=200)),
                ("story", models.JSONField(blank=True, default=list)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("members", "Members only"),
                            ("private", "Private"),
                        ],
                        default="members",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("follower", "following")},
            },
        ),
    ]
