# Generated by Django 4.2.27 on 2026-03-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_memberprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="uid",
            field=models.CharField(blank=True, db_index=True, default="", max_length=6),
        ),
    ]
