# Generated by Django 4.2.27 on 2026-03-03 22:12

import random
import string

from django.db import migrations, models


def generate_uid():
    alphabet = string.ascii_lowercase + string.digits
    return "".join(random.choices(alphabet, k=6))


def populate_uids(apps, schema_editor):
    MemberProfile = apps.get_model("members", "MemberProfile")
    used = set(
        MemberProfile.objects.exclude(uid="").values_list("uid", flat=True)
    )
    for profile in MemberProfile.objects.filter(uid=""):
        for _ in range(10):
            candidate = generate_uid()
            if candidate not in used:
                profile.uid = candidate
                profile.save(update_fields=["uid"])
                used.add(candidate)
                break


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_add_uid_field"),
    ]

    operations = [
        migrations.RunPython(populate_uids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="memberprofile",
            name="uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=6, unique=True
            ),
        ),
    ]
